---

- hosts: all
  tasks:

  - name: install apache and php & update repository Ubuntu
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php & update repository RedHat
    package:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat"

