---
- hosts: all
  tasks:

  - name: install apache and php & update repository
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
