---
- hosts: all
  pre_tasks:

  - name: install updates (RedHat)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  tasks:

  - name: install apache and php Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php RedHat
    tags: apache,redhat,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

- hosts: db_servers
  tasks:
  - name: install mariadb package (RedHat)
    tags: redhat,db,mariadb
    yum:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  tasks:
    - name: install samba on both Ubuntu AND RedHat
      tags: samba
      package:
        name:
          - samba
        state: latest
