---
- hosts: all
  pre_tasks:

  - name: install updates (RedHat)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"


  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  tasks:
  - name: add an SSH key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL5nmQNMvttIYZ9Rc4gnYe/Pj5XogutV6/4HbDDyt+q7 ansible"

- hosts: workstations
  tasks:
  - name: install unzip
    tags: unzip,terraform
    package:
      name: unzip

  - name: install terraform
    tags: terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  tasks:

  - name: install apache and php Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php RedHat
    tags: apache,redhat,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: start httpd (RedHat)
    tags: apache,apache2,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"

  - name: change email address for admin (RedHat)
    tags: apache,httpd,redhat
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin root@localhost
    when: ansible_distribution == "RedHat"
    register: httpd_variable

  - name: restart httpd (RedHat)
    tags: apache,httpd,redhat
    service:
      name: httpd
      state: restarted
    when: httpd_variable.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: /home/ido/ansible_turorial/files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  tasks:
  - name: install mariadb package (RedHat)
    tags: redhat,db,mariadb
    yum:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  tasks:
    - name: install samba on both Ubuntu AND RedHat
      tags: samba
      package:
        name:
          - samba
        state: latest
