---
- hosts: all
  pre_tasks:

  - name: install updates (RedHat)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"


  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  roles:
    - base

- hosts: workstations
  roles:
    - workstations

- hosts: web_servers
  roles:
    - web_servers

- hosts: db_servers
  roles:
    - db_servers

- hosts: file_servers
  roles:
    - file_servers
