- name: install mariadb package (RedHat)
  tags: redhat,db,mariadb
  yum:
    name:
      - mariadb-server
    state: latest
  when: ansible_distribution == "RedHat"

- name: install mariadb package (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name:
      - mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
